version = 1
SPDX-PackageName = "Gardener ext-authz-server"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/ext-authz-server"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"
